version: "3.9"
services:
  movie:
    build: ./movie/
    ports:
      - "3200:3200"
    volumes:
      - ./constants.py:/app/constants.py
    networks:
      - app-network
  showtime:
    build: ./showtime/
    ports:
      - "3202:3202"
    volumes:
      - ./constants.py:/app/constants.py
    networks:
      - app-network
  user:
    build: ./user/
    ports:
      - "3203:3203"
    volumes:
      - ./constants.py:/app/constants.py
    networks:
      - app-network
  booking:
    build: ./booking/
    ports:
      - "3201:3201"
    volumes:
      - ./constants.py:/app/constants.py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
